# CMake generated Testfile for 
# Source directory: L:/CppProject/GenesisEngine/tests
# Build directory: L:/CppProject/GenesisEngine/build-debug/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("L:/CppProject/GenesisEngine/build-debug/tests/genesis_engine_tests[1]_include.cmake")
add_test([=[GenesisRuntime_Smoke]=] "E:/msys64/mingw64/bin/cmake.exe" "-E" "env" "PATH=L:/CppProject/GenesisEngine/build-debug/tests;L:/CppProject/GenesisEngine/build-debug/src;C:\\Program Files\\PowerShell\\7;C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\.tmpBonq4c;C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@openai\\codex\\vendor\\x86_64-pc-windows-msvc\\path;L:\\Dev\\Scripts;L:\\Dev;C:\\program files (x86)\\imagemagick-6.2.7-q16;G:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit;L:\\Dev\\NodeJs;L:\\Java\\bin;L:\\Lib\\java;L:\\vcpkg;L:\\xampp\\php;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files\\PowerShell\\7;C:\\ProgramData\\chocolatey\\bin;E:\\msys64\\mingw64\\bin;L:\\Netbird;C:\\Users\\Administrator\\.local\\bin;C:\\Users\\Administrator\\.cargo\\bin;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Administrator\\.dotnet\\tools;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;L:\\flutter\\bin;C:\\Users\\Administrator\\AppData\\Roaming\\npm;G:\\Program Files\\cpolar;G:\\Program Files\\MKVToolNix;G:\\Program Files\\ffmpeg\\bin;L:\\Dev\\cmake\\bin;L:\\Lib\\vcpkg;C:\\Users\\Administrator\\AppData\\Roaming\\Composer\\vendor\\bin;G:\\SteamLibrary\\steamapps\\common\\Godot Engine;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama;C:\\Users\\Administrator\\.dotnet\\tools;E:\\msys64\\usr\\bin" "genesis_runtime_tests")
set_tests_properties([=[GenesisRuntime_Smoke]=] PROPERTIES  WORKING_DIRECTORY "L:/CppProject/GenesisEngine/build-debug/tests" _BACKTRACE_TRIPLES "L:/CppProject/GenesisEngine/tests/CMakeLists.txt;37;add_test;L:/CppProject/GenesisEngine/tests/CMakeLists.txt;0;")
add_test([=[GenesisEngine_E2E]=] "L:/CppProject/GenesisEngine/build-debug/src/genesis-engine.exe" "--steps=60" "--telemetry-file" "L:/CppProject/GenesisEngine/build-debug/telemetry_e2e.json")
set_tests_properties([=[GenesisEngine_E2E]=] PROPERTIES  WORKING_DIRECTORY "L:/CppProject/GenesisEngine/build-debug" _BACKTRACE_TRIPLES "L:/CppProject/GenesisEngine/tests/CMakeLists.txt;46;add_test;L:/CppProject/GenesisEngine/tests/CMakeLists.txt;0;")
add_test([=[GenesisSandboxCLI_Script]=] "E:/msys64/mingw64/bin/cmake.exe" "-E" "env" "PATH=L:/CppProject/GenesisEngine/build-debug/src;C:\\Program Files\\PowerShell\\7;C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\.tmpBonq4c;C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@openai\\codex\\vendor\\x86_64-pc-windows-msvc\\path;L:\\Dev\\Scripts;L:\\Dev;C:\\program files (x86)\\imagemagick-6.2.7-q16;G:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit;L:\\Dev\\NodeJs;L:\\Java\\bin;L:\\Lib\\java;L:\\vcpkg;L:\\xampp\\php;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files\\PowerShell\\7;C:\\ProgramData\\chocolatey\\bin;E:\\msys64\\mingw64\\bin;L:\\Netbird;C:\\Users\\Administrator\\.local\\bin;C:\\Users\\Administrator\\.cargo\\bin;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Administrator\\.dotnet\\tools;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;L:\\flutter\\bin;C:\\Users\\Administrator\\AppData\\Roaming\\npm;G:\\Program Files\\cpolar;G:\\Program Files\\MKVToolNix;G:\\Program Files\\ffmpeg\\bin;L:\\Dev\\cmake\\bin;L:\\Lib\\vcpkg;C:\\Users\\Administrator\\AppData\\Roaming\\Composer\\vendor\\bin;G:\\SteamLibrary\\steamapps\\common\\Godot Engine;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Ollama;C:\\Users\\Administrator\\.dotnet\\tools;E:\\msys64\\usr\\bin" "L:/CppProject/GenesisEngine/build-debug/src/genesis-sandbox-cli.exe" "--layout" "L:/CppProject/GenesisEngine/data/ascii_layout.json" "--commands" "step 5;pause;resume;step 3;quit" "--no-clear")
set_tests_properties([=[GenesisSandboxCLI_Script]=] PROPERTIES  DEPENDS "GenesisEngine_E2E" WORKING_DIRECTORY "L:/CppProject/GenesisEngine/build-debug" _BACKTRACE_TRIPLES "L:/CppProject/GenesisEngine/tests/CMakeLists.txt;52;add_test;L:/CppProject/GenesisEngine/tests/CMakeLists.txt;0;")
